name: CI/CD is Easy!

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: actions/checkout@main
        with:
          nnode-version: '16'
      - run: npm ci
      - run: npm install
      - run: npm run build

      
