name: Build Next.js web app
on: push
  
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main
      - name: Installing portfolio dependencies
        run: npm ci
      - name: run build failure
        run: npx browserslist@latest --update-db
      - name: Build project for production
        run: npm run build

      
