name: Build Next.js web app
on: push
  
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Installing portfolio dependencies
        run: npm ci
      - name: Build project for production
        run: npm run build
